package vista.ventana;

import servicio.SistemaVideoClub;
import javax.swing.JFrame;

public class MenuVentana extends javax.swing.JPanel {

    private SistemaVideoClub sistema;
    
    public MenuVentana() {
        initComponents();
    }

    public MenuVentana(SistemaVideoClub sistema) {
        initComponents();
        this.sistema = sistema;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEmpleadosActionPerformed = new javax.swing.JButton();
        btnPeliculasActionPerformed = new javax.swing.JButton();
        btnClientesActionPerformed = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnEmpleadosActionPerformed.setText("Menu empleados");
        btnEmpleadosActionPerformed.addActionListener(this::btnEmpleadosActionPerformedActionPerformed);

        btnPeliculasActionPerformed.setText("Menu peliculas");
        btnPeliculasActionPerformed.addActionListener(this::btnPeliculasActionPerformedActionPerformed);

        btnClientesActionPerformed.setText("Menu clientes");
        btnClientesActionPerformed.addActionListener(this::btnClientesActionPerformedActionPerformed);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Video-Club");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnClientesActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPeliculasActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEmpleadosActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(btnClientesActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPeliculasActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpleadosActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPeliculasActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculasActionPerformedActionPerformed
        JFrame marco = new JFrame("Menu peliculas");
        marco.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        marco.add(new VentanaPelicula(sistema));
        marco.pack();
        marco.setLocationRelativeTo(this);
        marco.setVisible(true);
    }//GEN-LAST:event_btnPeliculasActionPerformedActionPerformed

    private void btnEmpleadosActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformedActionPerformed
        JFrame marco = new JFrame("Menu empleados");
        marco.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        marco.add(new VentanaEmpleado(sistema));
        marco.pack();
        marco.setLocationRelativeTo(this);
        marco.setVisible(true);
    }//GEN-LAST:event_btnEmpleadosActionPerformedActionPerformed

    private void btnClientesActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformedActionPerformed
        // TODO add your handling code here:
        JFrame marco = new JFrame("Menu clientes");
        marco.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        marco.add(new VentanaCliente(sistema));
        marco.pack();
        marco.setLocationRelativeTo(this);
        marco.setVisible(true);
        
    }//GEN-LAST:event_btnClientesActionPerformedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientesActionPerformed;
    private javax.swing.JButton btnEmpleadosActionPerformed;
    private javax.swing.JButton btnPeliculasActionPerformed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

