package vista.ventana;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import servicio.SistemaVideoClub;
public class VentanaAccionesCliente extends javax.swing.JPanel {

    SistemaVideoClub sistema;
    String rutCliente;
    /**
     * Creates new form MenuVentana
     */
    public VentanaAccionesCliente() {
        initComponents();
    }
    
    public VentanaAccionesCliente(SistemaVideoClub sistema, String rut) {
        initComponents();
        this.sistema = sistema;
        this.rutCliente = rut;
        
        lblRutCliente.setText("RUT cliente actual: " + this.rutCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRutCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMostrarClienteActionPerformed = new javax.swing.JButton();
        btnRenovarPrestamoActionPerformed = new javax.swing.JButton();
        btnPagarMultaActionPerformed = new javax.swing.JButton();
        btnDevolverPeliculaActionPerformed = new javax.swing.JButton();
        btnPedirPeliculaActionPerformed = new javax.swing.JButton();
        btnRenovarPrestamoDiasEspecificosActionPerformed = new javax.swing.JButton();
        btnSalirActionPerformed = new javax.swing.JButton();

        lblRutCliente.setText("Rut cliente actual: ");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acciones cliente");
        jLabel1.setToolTipText("");

        btnMostrarClienteActionPerformed.setText("Mostrar datos");
        btnMostrarClienteActionPerformed.addActionListener(this::btnMostrarClienteActionPerformedActionPerformed);

        btnRenovarPrestamoActionPerformed.setText("Renovar prestamo");
        btnRenovarPrestamoActionPerformed.addActionListener(this::btnRenovarPrestamoActionPerformedActionPerformed);

        btnPagarMultaActionPerformed.setText("Pagar multa");
        btnPagarMultaActionPerformed.addActionListener(this::btnPagarMultaActionPerformedActionPerformed);

        btnDevolverPeliculaActionPerformed.setText("Devolver pelicula");
        btnDevolverPeliculaActionPerformed.addActionListener(this::btnDevolverPeliculaActionPerformedActionPerformed);

        btnPedirPeliculaActionPerformed.setText("Pedir pelicula");
        btnPedirPeliculaActionPerformed.addActionListener(this::btnPedirPeliculaActionPerformedActionPerformed);

        btnRenovarPrestamoDiasEspecificosActionPerformed.setText("Renovar por dias");
        btnRenovarPrestamoDiasEspecificosActionPerformed.addActionListener(this::btnRenovarPrestamoDiasEspecificosActionPerformedActionPerformed);

        btnSalirActionPerformed.setText("Salir");
        btnSalirActionPerformed.addActionListener(this::btnSalirActionPerformedActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPedirPeliculaActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRenovarPrestamoActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRutCliente)
                    .addComponent(btnSalirActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDevolverPeliculaActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPagarMultaActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRenovarPrestamoDiasEspecificosActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostrarClienteActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(lblRutCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedirPeliculaActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRenovarPrestamoActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRenovarPrestamoDiasEspecificosActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDevolverPeliculaActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarClienteActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarMultaActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalirActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedirPeliculaActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirPeliculaActionPerformedActionPerformed
        // TODO add your handling code here:
        String inputId = JOptionPane.showInputDialog(this, "Ingrese el ID de la película a pedir:", "Pedir Película", JOptionPane.QUESTION_MESSAGE);
        if (inputId != null && !inputId.trim().isEmpty()) {
            try {
                int id = Integer.parseInt(inputId.trim());
                // Llama a tu método prestar en el sistema
                String resultado = sistema.prestar(id, this.rutCliente);
                JOptionPane.showMessageDialog(this, resultado, "Resultado Préstamo", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnPedirPeliculaActionPerformedActionPerformed

    private void btnDevolverPeliculaActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverPeliculaActionPerformedActionPerformed
        // TODO add your handling code here:
        String inputId = JOptionPane.showInputDialog(this, "Ingrese el ID de la película a devolver:", "Devolver Película", JOptionPane.QUESTION_MESSAGE);
        if (inputId != null && !inputId.trim().isEmpty()) {
            try {
                int id = Integer.parseInt(inputId.trim());
                String resultado = sistema.recibirPeliculaPrestada(id, this.rutCliente);
                JOptionPane.showMessageDialog(this, resultado, "Resultado Devolución", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDevolverPeliculaActionPerformedActionPerformed

    private void btnPagarMultaActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMultaActionPerformedActionPerformed
        // TODO add your handling code here:
        String inputMonto = JOptionPane.showInputDialog(this, "Ingrese el monto entregado por el cliente:", "Pagar Multa", JOptionPane.QUESTION_MESSAGE);
        if (inputMonto != null && !inputMonto.trim().isEmpty()) {
            try {
                double monto = Double.parseDouble(inputMonto.trim());
                String resultado = sistema.recibirPago(monto, this.rutCliente);
                JOptionPane.showMessageDialog(this, resultado, "Comprobante de Pago", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese un monto monetario válido (ejemplo: 5000 u 8000.50).", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnPagarMultaActionPerformedActionPerformed

    private void btnRenovarPrestamoActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenovarPrestamoActionPerformedActionPerformed
        // TODO add your handling code here:
        String inputId = JOptionPane.showInputDialog(this, "Ingrese el ID de la película a renovar:", "Renovar Préstamo", JOptionPane.QUESTION_MESSAGE);
        if (inputId != null && !inputId.trim().isEmpty()) {
            try {
                int id = Integer.parseInt(inputId.trim());
                String resultado = sistema.renovar(id, this.rutCliente);
                JOptionPane.showMessageDialog(this, resultado, "Resultado Renovación", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRenovarPrestamoActionPerformedActionPerformed

    private void btnRenovarPrestamoDiasEspecificosActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenovarPrestamoDiasEspecificosActionPerformedActionPerformed
        // TODO add your handling code here:
        String inputId = JOptionPane.showInputDialog(this, "Ingrese el ID de la película:", "Renovar por Días", JOptionPane.QUESTION_MESSAGE);
        if (inputId != null && !inputId.trim().isEmpty()) {
            String inputDias = JOptionPane.showInputDialog(this, "Ingrese la cantidad de días a renovar (máx 7):", "Renovar por Días", JOptionPane.QUESTION_MESSAGE);
            if (inputDias != null && !inputDias.trim().isEmpty()) {
                try {
                    int id = Integer.parseInt(inputId.trim());
                    int dias = Integer.parseInt(inputDias.trim());

                    String resultado = sistema.renovar(id, this.rutCliente, dias);
                    JOptionPane.showMessageDialog(this, resultado, "Resultado Renovación Custom", JOptionPane.INFORMATION_MESSAGE);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Tanto el ID como los días deben ser valores numéricos enteros.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnRenovarPrestamoDiasEspecificosActionPerformedActionPerformed

    private void btnMostrarClienteActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarClienteActionPerformedActionPerformed
        // TODO add your handling code here:
        String datos = sistema.mostrarCliente(this.rutCliente);
    
        JTextArea textArea = new JTextArea(10, 25);
        textArea.setText(datos);
        textArea.setEditable(false);

        JOptionPane.showMessageDialog(this, new JScrollPane(textArea), "Ficha del Cliente", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnMostrarClienteActionPerformedActionPerformed

    private void btnSalirActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformedActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolverPeliculaActionPerformed;
    private javax.swing.JButton btnMostrarClienteActionPerformed;
    private javax.swing.JButton btnPagarMultaActionPerformed;
    private javax.swing.JButton btnPedirPeliculaActionPerformed;
    private javax.swing.JButton btnRenovarPrestamoActionPerformed;
    private javax.swing.JButton btnRenovarPrestamoDiasEspecificosActionPerformed;
    private javax.swing.JButton btnSalirActionPerformed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRutCliente;
    // End of variables declaration//GEN-END:variables
}